/*
-- Query: SELECT * FROM positivo_chiperia.conceptos
LIMIT 0, 1000

-- Date: 2016-06-25 13:04
*/
INSERT INTO `conceptos` (`ID_CONCEPTO`,`DESCRIPCION`,`SIGNO`) VALUES (2,'VENTAS','D');
INSERT INTO `conceptos` (`ID_CONCEPTO`,`DESCRIPCION`,`SIGNO`) VALUES (1,'COMPRAS','C');
INSERT INTO `conceptos` (`ID_CONCEPTO`,`DESCRIPCION`,`SIGNO`) VALUES (8,'AJUSTE DE INVENTARIO','C');
INSERT INTO `conceptos` (`ID_CONCEPTO`,`DESCRIPCION`,`SIGNO`) VALUES (30,'FABRICA','C');
INSERT INTO `conceptos` (`ID_CONCEPTO`,`DESCRIPCION`,`SIGNO`) VALUES (10,'PEDIDOS','D');
INSERT INTO `conceptos` (`ID_CONCEPTO`,`DESCRIPCION`,`SIGNO`) VALUES (40,'REINICIAR STOCK','');
